name: BrowserStack Application
on:
  push:
    branches:
      - '**'
jobs:
  ubuntu-job:
    name: 'BrowserStack Test to run Login'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME
      - name: Running requirements and server in  background
        uses: 'actions/checkout@v2'
      - name: Setup to run test
        run: |
              pip install -r requirements.txt
              python browserstackcansrapplogin.py